name: nanopore_workflow
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - aioeasywebdav=2.4.0=py38h578d9bd_1001
  - aiohttp=3.7.4.post0=py38h497a2fe_0
  - alsa-lib=1.2.3=h516909a_0
  - amply=0.1.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - atk-1.0=2.36.0=h3371d22_4
  - attmap=0.13.0=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bc=1.07.1=h7f98852_0
  - bcftools=1.12=h45bccc9_1
  - bcrypt=3.2.0=py38h497a2fe_1
  - bedtools=2.30.0=h7d7f7ad_1
  - binutils_impl_linux-64=2.35.1=h193b22a_2
  - binutils_linux-64=2.35=h67ddf6f_30
  - bioconductor-annotationdbi=1.50.0=r40_0
  - bioconductor-annotationfilter=1.12.0=r40_0
  - bioconductor-bamsignals=1.20.0=r40h5f743cb_0
  - bioconductor-beachmat=2.4.0=r40h5f743cb_0
  - bioconductor-biobase=2.48.0=r40h037d062_0
  - bioconductor-biocfilecache=1.12.0=r40_0
  - bioconductor-biocgenerics=0.34.0=r40_0
  - bioconductor-biocparallel=1.22.0=r40h5f743cb_0
  - bioconductor-biomart=2.44.0=r40_0
  - bioconductor-biostrings=2.56.0=r40h037d062_0
  - bioconductor-biovizbase=1.36.0=r40h037d062_0
  - bioconductor-bsgenome=1.56.0=r40_0
  - bioconductor-bsseq=1.24.0=r40h5f743cb_0
  - bioconductor-delayedarray=0.14.0=r40h037d062_0
  - bioconductor-delayedmatrixstats=1.10.0=r40_0
  - bioconductor-dss=2.36.0=r40h037d062_0
  - bioconductor-ensembldb=2.12.1=r40_0
  - bioconductor-genomeinfodb=1.24.0=r40_0
  - bioconductor-genomeinfodbdata=1.2.4=r40_0
  - bioconductor-genomicalignments=1.24.0=r40h037d062_0
  - bioconductor-genomicfeatures=1.40.0=r40_0
  - bioconductor-genomicranges=1.40.0=r40h037d062_0
  - bioconductor-hdf5array=1.16.0=r40h037d062_0
  - bioconductor-iranges=2.22.1=r40h037d062_0
  - bioconductor-karyoploter=1.14.0=r40_0
  - bioconductor-limma=3.44.1=r40h037d062_0
  - bioconductor-org.hs.eg.db=3.11.4=r40_1
  - bioconductor-protgenerics=1.20.0=r40_0
  - bioconductor-regioner=1.20.0=r40_0
  - bioconductor-rhdf5=2.32.0=r40h5f743cb_0
  - bioconductor-rhdf5lib=1.10.0=r40h037d062_0
  - bioconductor-rhtslib=1.20.0=r40h037d062_0
  - bioconductor-rsamtools=2.4.0=r40h5f743cb_0
  - bioconductor-rtracklayer=1.48.0=r40h037d062_0
  - bioconductor-s4vectors=0.26.0=r40h037d062_0
  - bioconductor-summarizedexperiment=1.18.1=r40_0
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene=3.10.0=r40_1
  - bioconductor-variantannotation=1.34.0=r40h037d062_0
  - bioconductor-xvector=0.28.0=r40h037d062_0
  - bioconductor-zlibbioc=1.34.0=r40h037d062_0
  - biopython=1.79=py38h497a2fe_0
  - blast=2.5.0=hc0b0e79_3
  - boost=1.76.0=py38hfc89cab_0
  - boost-cpp=1.76.0=h312852a_1
  - boto3=1.18.54=pyhd8ed1ab_0
  - botocore=1.21.54=pyhd8ed1ab_0
  - bowtie2=2.2.5=py38h8c62d01_8
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bwa=0.7.17=h5bf99c6_8
  - bwidget=1.9.14=ha770c72_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - canu=2.1.1=h1b792b2_2
  - capnproto=0.6.1=hfc679d8_1
  - certifi=2021.10.8=py38h578d9bd_1
  - cffi=1.14.6=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - chrpath=0.16=h7f98852_1002
  - cigar=0.1.3=pyh864c0ab_1
  - coincbc=2.10.5=hcee13e7_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda=4.11.0=py38h578d9bd_0
  - conda-package-handling=1.7.3=py38h497a2fe_0
  - configargparse=1.5.3=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - curl=7.79.1=h2574ce0_1
  - cutesv=1.0.11=pyhdfd78af_0
  - cycler=0.10.0=py_2
  - datrie=0.8.2=py38h497a2fe_2
  - dbus=1.13.6=h48d8840_2
  - decorator=4.4.2=py_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - docutils=0.17.1=py38h578d9bd_0
  - dropbox=11.20.0=pyhd8ed1ab_0
  - eigen=3.4.0=h4bd325d_0
  - expat=2.4.1=h9c3ff4c_0
  - fftw=3.3.9=nompi_h74d3f13_101
  - filechunkio=1.8=py_2
  - filelock=3.3.0=pyhd8ed1ab_0
  - flye=2.8.3=py38h69e0bdc_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freebayes=1.3.5=py38ha193a2f_3
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - ftputil=5.0.1=pyhd8ed1ab_0
  - gcc_impl_linux-64=9.3.0=h70c0ae5_19
  - gcc_linux-64=9.3.0=hf25ea35_30
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gettext=0.19.8.1=h0b5b191_1005
  - gfortran_impl_linux-64=9.3.0=hc4a2995_19
  - gfortran_linux-64=9.3.0=hdc58fab_30
  - ghostscript=9.54.0=h9c3ff4c_1
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnuplot=5.4.1=hec6539f_2
  - google-api-core=1.31.2=pyhd8ed1ab_0
  - google-api-python-client=2.23.0=pyhd8ed1ab_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_0
  - google-cloud-core=1.7.2=pyh6c4a22f_0
  - google-cloud-storage=1.19.0=py_0
  - google-crc32c=1.1.2=py38h8838a9a_0
  - google-resumable-media=2.0.3=pyh6c4a22f_0
  - googleapis-common-protos=1.53.0=py38h578d9bd_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.49.1=h85b4f2f_0
  - grpcio=1.38.1=py38hdd6454d_0
  - gsl=2.6=he838d99_2
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - gxx_impl_linux-64=9.3.0=hd87eabc_19
  - gxx_linux-64=9.3.0=h3fbe746_30
  - harfbuzz=2.9.1=h83ec7ef_1
  - hdf5=1.8.18=3
  - htslib=1.12=h9093b5e_1
  - httplib2=0.19.1=pyhd8ed1ab_0
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - imagemagick=7.1.0_4=pl5321hb118871_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipython_genutils=0.2.0=py_1
  - isa-l=2.30.0=ha770c72_4
  - jbig=2.1=h7f98852_2003
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joypy=0.2.4=pyhd3deb0d_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=4.0.1=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py38h578d9bd_0
  - k8=0.2.5=h9a82719_1
  - kernel-headers_linux-64=2.6.32=he073ed8_14
  - kiwisolver=1.3.2=py38h1fd1430_0
  - krb5=1.19.2=hcc1bbae_2
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcrc32c=1.1.1=h9c3ff4c_2
  - libcurl=7.79.1=h2574ce0_1
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-devel_linux-64=9.3.0=h7864c58_19
  - libgcc-ng=11.2.0=h1d223b6_9
  - libgd=2.3.3=h6ad9fb6_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.2.0=h1d223b6_9
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.43.0=h812cca2_1
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.10=pthreads_h4812303_5
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.18.0=h780b84a_1
  - librsvg=2.52.0=hc3c00ef_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-devel_linux-64=9.3.0=hb016644_19
  - libstdcxx-ng=11.2.0=he4da1e4_9
  - libtiff=4.3.0=hf544144_1
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.1=h3452ae3_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - logmuse=0.2.6=pyh8c360ce_0
  - longshot=0.4.1=h123da94_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - make=4.3=hd18ef5c_1
  - mappy=2.17=py38h390ddb8_3
  - markupsafe=2.0.1=py38h497a2fe_0
  - mash=2.3=he348c14_1
  - matplotlib=3.4.2=py38h578d9bd_0
  - matplotlib-base=3.4.2=py38hcc49a3a_0
  - merqury=1.3=hdfd78af_0
  - meryl=1.3=h1b792b2_0
  - miniasm=0.3_r179=h5bf99c6_2
  - minimap2=2.22=h5bf99c6_0
  - more-itertools=8.10.0=pyhd8ed1ab_0
  - multidict=5.2.0=py38h497a2fe_0
  - muscle=3.8.1551=h7d875b9_6
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nanofilt=2.8.0=py_0
  - nanoget=1.16.1=py_0
  - nanomath=1.2.1=pyhdfd78af_0
  - nanoplot=1.20.0=py_1
  - nanoplotter=1.10.0=py_1
  - nanopolish=0.13.2=ha140323_4
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - networkx=2.6.3=pyhd8ed1ab_0
  - ngmlr=0.2.7=h9a82719_3
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_1
  - numpy=1.21.2=py38he2449b9_0
  - oauth2client=4.1.3=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjdk=11.0.9.1=h5cc2fde_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py38h43a58ef_0
  - pandoc=2.14.2=h7f98852_0
  - pango=1.48.10=hb8ff022_1
  - parallel=20210822=ha770c72_0
  - paramiko=2.7.2=pyh9f0ad1d_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pauvre=0.1.86=py_1
  - pbzip2=1.1.13=0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=h032f7d1_0
  - peppy=0.31.1=pyhd8ed1ab_0
  - perl=5.32.1=0_h7f98852_perl5
  - perl-filesys-df=0.92=1
  - perl-threaded=5.26.0=0
  - pigz=2.6=h27826a3_0
  - pillow=8.3.2=py38h8e6f84c_0
  - pilon=1.24=hdfd78af_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - plotly=5.3.1=pyhd8ed1ab_0
  - pluggy=1.0.0=py38h578d9bd_1
  - ply=3.11=py_1
  - prettytable=2.2.1=pyhd8ed1ab_0
  - primer3=2.0.0a=h779adbc_4
  - protobuf=3.18.0=py38h709712a_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.5.0=py38h578d9bd_0
  - py=1.10.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybedtools=0.8.2=py38h69e0bdc_1
  - pycosat=0.6.3=py38h497a2fe_1006
  - pycparser=2.20=pyh9f0ad1d_2
  - pyfaidx=0.6.2=pyh5e36f6f_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pygraphviz=1.7=py38h0d738da_0
  - pynacl=1.4.0=py38h497a2fe_2
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysam=0.16.0.1=py38hf7546f9_3
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py38h578d9bd_3
  - pytest=6.2.5=py38h578d9bd_0
  - python=3.8.10=h49503c6_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-edlib=1.3.9=py38h8c62d01_0
  - python-irodsclient=1.0.0=pyhd8ed1ab_0
  - python-isal=0.11.1=py38h497a2fe_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyvcf=0.6.8=py38h32f6830_1002
  - pyyaml=5.4.1=py38h497a2fe_1
  - qt=5.12.9=hda022c4_4
  - r-acepack=1.4.1=r40h859d828_1006
  - r-ape=5.5=r40h306847c_0
  - r-argparse=2.1.1=r40hc72bb7e_0
  - r-askpass=1.1=r40hcfec24a_2
  - r-assertthat=0.2.1=r40hc72bb7e_2
  - r-backports=1.2.1=r40hcfec24a_0
  - r-base=4.0.5=hb67fd72_2
  - r-base64enc=0.1_3=r40hcfec24a_1004
  - r-bezier=1.1.2=r40hc72bb7e_1002
  - r-bh=1.75.0_0=r40hc72bb7e_0
  - r-bit=4.0.4=r40hcfec24a_0
  - r-bit64=4.0.5=r40hcfec24a_0
  - r-bitops=1.0_7=r40hcfec24a_0
  - r-blob=1.2.2=r40hc72bb7e_0
  - r-brio=1.1.2=r40hcfec24a_0
  - r-broom=0.7.9=r40hc72bb7e_0
  - r-cachem=1.0.6=r40hcfec24a_0
  - r-callr=3.7.0=r40hc72bb7e_0
  - r-cellranger=1.1.0=r40hc72bb7e_1003
  - r-checkmate=2.0.0=r40hcfec24a_1
  - r-cli=3.0.1=r40h03ef668_1
  - r-clipr=0.7.1=r40hc72bb7e_0
  - r-cluster=2.1.2=r40h859d828_0
  - r-colorspace=2.0_2=r40hcfec24a_0
  - r-cpp11=0.4.0=r40hc72bb7e_0
  - r-crayon=1.4.1=r40hc72bb7e_0
  - r-curl=4.3.2=r40hcfec24a_0
  - r-data.table=1.14.2=r40hcfec24a_0
  - r-dbi=1.1.1=r40hc72bb7e_0
  - r-dbplyr=2.1.1=r40hc72bb7e_0
  - r-desc=1.4.0=r40hc72bb7e_0
  - r-dichromat=2.0_0=r40ha770c72_2002
  - r-diffobj=0.3.4=r40hcfec24a_0
  - r-digest=0.6.28=r40h03ef668_0
  - r-dplyr=1.0.7=r40h03ef668_0
  - r-dtplyr=1.1.0=r40hc72bb7e_0
  - r-ellipsis=0.3.2=r40hcfec24a_0
  - r-evaluate=0.14=r40hc72bb7e_2
  - r-fansi=0.5.0=r40hcfec24a_0
  - r-farver=2.1.0=r40h03ef668_0
  - r-fastmap=1.1.0=r40h03ef668_0
  - r-fastmatch=1.1_3=r40hcfec24a_0
  - r-findpython=1.0.7=r40hc72bb7e_0
  - r-forcats=0.5.1=r40hc72bb7e_0
  - r-foreign=0.8_81=r40hcfec24a_0
  - r-formatr=1.11=r40hc72bb7e_0
  - r-formula=1.2_4=r40hc72bb7e_0
  - r-fs=1.5.0=r40h03ef668_0
  - r-futile.logger=1.4.3=r40hc72bb7e_1003
  - r-futile.options=1.0.1=r40hc72bb7e_1002
  - r-gargle=1.2.0=r40hc72bb7e_0
  - r-generics=0.1.0=r40hc72bb7e_0
  - r-ggplot2=3.3.5=r40hc72bb7e_0
  - r-glue=1.4.2=r40hcfec24a_0
  - r-googledrive=2.0.0=r40hc72bb7e_0
  - r-googlesheets4=1.0.0=r40h785f33e_0
  - r-gridextra=2.3=r40hc72bb7e_1003
  - r-gtable=0.3.0=r40hc72bb7e_3
  - r-gtools=3.9.2=r40hcfec24a_0
  - r-haven=2.4.3=r40h2713e49_0
  - r-highr=0.9=r40hc72bb7e_0
  - r-hmisc=4.5_0=r40h859d828_0
  - r-hms=1.1.1=r40hc72bb7e_0
  - r-htmltable=2.2.1=r40hc72bb7e_0
  - r-htmltools=0.5.2=r40h03ef668_0
  - r-htmlwidgets=1.5.4=r40hc72bb7e_0
  - r-httr=1.4.2=r40hc72bb7e_0
  - r-ids=1.0.1=r40hc72bb7e_1
  - r-igraph=1.2.6=r40he0372cf_1
  - r-isoband=0.2.5=r40h03ef668_0
  - r-jpeg=0.1_9=r40hcfec24a_0
  - r-jquerylib=0.1.4=r40hc72bb7e_0
  - r-jsonlite=1.7.2=r40hcfec24a_0
  - r-knitr=1.36=r40hc72bb7e_0
  - r-labeling=0.4.2=r40hc72bb7e_0
  - r-lambda.r=1.2.4=r40hc72bb7e_1
  - r-lattice=0.20_45=r40hcfec24a_0
  - r-latticeextra=0.6_29=r40hc72bb7e_1
  - r-lazyeval=0.2.2=r40hcfec24a_2
  - r-lifecycle=1.0.1=r40hc72bb7e_0
  - r-locfit=1.5_9.4=r40hcfec24a_1
  - r-lubridate=1.7.10=r40h03ef668_0
  - r-magrittr=2.0.1=r40hcfec24a_1
  - r-markdown=1.1=r40hcfec24a_1
  - r-mass=7.3_54=r40hcfec24a_0
  - r-matrix=1.3_4=r40he454529_0
  - r-matrixstats=0.61.0=r40hcfec24a_0
  - r-memoise=2.0.0=r40hc72bb7e_0
  - r-mgcv=1.8_37=r40he454529_0
  - r-mime=0.12=r40hcfec24a_0
  - r-modelr=0.1.8=r40hc72bb7e_0
  - r-munsell=0.5.0=r40hc72bb7e_1003
  - r-nlme=3.1_152=r40h859d828_0
  - r-nnet=7.3_16=r40hcfec24a_0
  - r-openssl=1.4.5=r40he36bf35_0
  - r-permute=0.9_5=r40h785f33e_3
  - r-phangorn=2.7.1=r40h6dc32e9_0
  - r-pillar=1.6.3=r40hc72bb7e_0
  - r-pkgconfig=2.0.3=r40hc72bb7e_1
  - r-pkgload=1.2.2=r40h03ef668_0
  - r-plogr=0.2.0=r40hc72bb7e_1003
  - r-plyr=1.8.6=r40h03ef668_1
  - r-png=0.1_7=r40hcfec24a_1004
  - r-praise=1.0.0=r40hc72bb7e_1004
  - r-prettyunits=1.1.1=r40hc72bb7e_1
  - r-processx=3.5.2=r40hcfec24a_0
  - r-progress=1.2.2=r40hc72bb7e_2
  - r-ps=1.6.0=r40hcfec24a_0
  - r-purrr=0.3.4=r40hcfec24a_1
  - r-quadprog=1.5_8=r40h742201e_3
  - r-r.methodss3=1.8.1=r40hc72bb7e_0
  - r-r.oo=1.24.0=r40hc72bb7e_0
  - r-r.utils=2.11.0=r40hc72bb7e_0
  - r-r6=2.5.1=r40hc72bb7e_0
  - r-rappdirs=0.3.3=r40hcfec24a_0
  - r-rcolorbrewer=1.1_2=r40h785f33e_1003
  - r-rcpp=1.0.7=r40h03ef668_0
  - r-rcurl=1.98_1.5=r40hcfec24a_0
  - r-readr=2.0.2=r40h03ef668_0
  - r-readxl=1.3.1=r40h2713e49_4
  - r-rematch=1.0.1=r40hc72bb7e_1003
  - r-rematch2=2.1.2=r40hc72bb7e_1
  - r-reprex=2.0.1=r40hc72bb7e_0
  - r-reshape2=1.4.4=r40h03ef668_1
  - r-rlang=0.4.11=r40hcfec24a_0
  - r-rmarkdown=2.11=r40hc72bb7e_0
  - r-rpart=4.1_15=r40hcfec24a_2
  - r-rprojroot=2.0.2=r40hc72bb7e_0
  - r-rsqlite=2.2.8=r40h03ef668_0
  - r-rstudioapi=0.13=r40hc72bb7e_0
  - r-rvest=1.0.1=r40hc72bb7e_0
  - r-scales=1.1.1=r40hc72bb7e_0
  - r-selectr=0.4_2=r40hc72bb7e_1
  - r-snow=0.4_3=r40hc72bb7e_1002
  - r-stringi=1.7.5=r40hcabe038_0
  - r-stringr=1.4.0=r40hc72bb7e_2
  - r-survival=3.2_13=r40hcfec24a_0
  - r-sys=3.4=r40hcfec24a_0
  - r-testthat=3.1.0=r40h03ef668_0
  - r-tibble=3.1.5=r40hcfec24a_0
  - r-tidyr=1.1.3=r40h03ef668_0
  - r-tidyselect=1.1.1=r40hc72bb7e_0
  - r-tidyverse=1.3.1=r40hc72bb7e_0
  - r-tinytex=0.34=r40hc72bb7e_0
  - r-tzdb=0.1.2=r40h03ef668_2
  - r-utf8=1.2.2=r40hcfec24a_0
  - r-uuid=0.1_4=r40hcfec24a_1
  - r-vctrs=0.3.8=r40hcfec24a_1
  - r-viridis=0.6.1=r40hc72bb7e_1
  - r-viridislite=0.4.0=r40hc72bb7e_0
  - r-vroom=1.5.5=r40h03ef668_1
  - r-waldo=0.3.1=r40hc72bb7e_0
  - r-withr=2.4.2=r40hc72bb7e_0
  - r-xfun=0.26=r40h03ef668_0
  - r-xml=3.99_0.8=r40hcfec24a_0
  - r-xml2=1.3.2=r40h03ef668_1
  - r-yaml=2.2.1=r40hcfec24a_1
  - racon=1.4.20=h9a82719_1
  - ratelimiter=1.2.0=py_1002
  - raven-assembler=1.6.0=h2e03b76_0
  - readline=8.1=h46c0cb4_0
  - requests=2.26.0=pyhd8ed1ab_0
  - rsa=4.7.2=pyh44b312d_0
  - ruamel_yaml=0.15.80=py38h497a2fe_1004
  - s3transfer=0.5.0=pyhd8ed1ab_0
  - samtools=1.12=h9aed4be_1
  - scipy=1.6.3=py38h7b17777_0
  - seaborn=0.10.0=py_1
  - sed=4.8=he412f7d_0
  - setuptools=58.0.4=py38h578d9bd_2
  - simplejson=3.17.5=py38h497a2fe_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=5.2.1=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=6.9.1=hdfd78af_0
  - snakemake-minimal=6.9.1=pyhdfd78af_0
  - sniffles=1.0.11=hdbcaa40_1
  - spades=3.13.0=0
  - sqlite=3.36.0=h9cd32fc_2
  - statsmodels=0.13.0=py38h6c62de6_0
  - stone=3.2.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - survivor=1.0.7=h9a82719_1
  - svim=1.4.2=py_0
  - sysroot_linux-64=2.12=he073ed8_14
  - tabix=1.11=hdfd78af_0
  - tabixpp=1.1.0=he28291e_6
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tclap=1.2.3=h9c3ff4c_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - tktable=2.10=hb7b940f_3
  - toml=0.10.2=pyhd8ed1ab_0
  - toposort=1.7=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.0=pyhd8ed1ab_0
  - trycycler=0.5.0=pyhdfd78af_0
  - typing-extensions=3.10.0.2=hd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - ubiquerg=0.6.1=pyh9f0ad1d_0
  - unicycler=0.4.8=py38h8162308_3
  - uritemplate=3.0.1=py_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - vcflib=1.0.2=h3198e80_5
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - whatshap=1.1=py38h8c62d01_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - winnowmap=2.03=h2e03b76_0
  - wrapt=1.12.1=py38h497a2fe_3
  - xmlrunner=1.7.7=py_0
  - xopen=1.2.0=py38h578d9bd_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h497a2fe_2
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0

